### ISSUE TITLE
next() resolves undefined on nested upsert

### ISSUE THREAD

**Issue by LucianBuzzo** [olivierwilkinson/prisma-nested-middleware#24] opened 2023-06-08 16:30 UTC
If I perform a nested upsert, then `next()` will always return `undefined`.
I expect that `next()` should return the upserted document, if it is available due to an `include` statement.

Below is minimal reproduction of the issue:

Schema:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id      Int      @id @default(autoincrement())
  email   String   @unique
  name    String?
  profile Profile?
}

model Profile {
  id     Int     @id @default(autoincrement())
  bio    String?
  age    Int?
  user   User?   @relation(fields: [userId], references: [id])
  userId Int?    @unique
  meta   Json?
}
```

Code

```ts
import { PrismaClient } from "@prisma/client";
import { createNestedMiddleware } from "prisma-nested-middleware";

const prisma = new PrismaClient();

prisma.$use(
	createNestedMiddleware(async (params, next) => {
		const result = await next(params);
		if (params.model === "Profile" && params.action === "upsert") {
			console.log("mdlwr Profile", result);
			console.log("mdlwr Params", params);
		}

		return result;
	}),
);

const run = async () => {
	const user = await prisma.user.upsert({
		create: {
			name: "Alice",
			email: "alice@test.com",
		},
		update: {
			name: "Alice",
			email: "alice@test.com",
		},
		where: {
			email: "alice@test.com",
		},
	});

	await prisma.user.update({
		where: {
			id: user.id,
		},
		data: {
			name: "Bob",
			profile: {
				upsert: {
					create: {
						bio: "I like turtles",
					},
					update: {
						bio: "I like turtles",
					},
				},
			},
		},
		include: {
			profile: true,
		},
	});
};

run();
```

When you run this code, the `result` value in the middleware is always `undefined` for `Profile` upserts.

Looking at the code, it seems that `next()` will always resolve to `undefined` if a write query is being performed.
If I comment out this line https://github.com/olivierwilkinson/prisma-nested-middleware/blob/main/src/lib/utils/targets.ts#L103 then the code behaves as expected, however I'm not 100% sure why this exists, and the `prisma-nested-middleware` unit tests fail if I remove it.

**Comment by olivierwilkinson** [comment] 2023-06-09 11:30
Hi there,

Thanks for raising this! I'll have a look into this soon and get back to you 👍

**Comment by olivierwilkinson** [comment] 2023-07-18 12:48
Heya,

Sorry for the slow response! 🙏 

So this is actually the expected behaviour since v3, the reason for the change is that it's not always possible to match the included results for a relation with the nested write. For example if the relation was a toMany relation, say "posts", it's not possible to match the upsert with the post that was operated on.

There is a way to modify the included results however, by using the 'include' and 'select' action types, for your example above you should be able to replace "upsert" with "include" and find the result is returned. There are some more details to consider so have a look at the [Modifying Results](https://github.com/olivierwilkinson/prisma-nested-middleware#modifying-results) section of the readme, let me know if it's unclear or needs more info 👍

I hope that is helpful!

**Comment by olivierwilkinson** [comment] 2023-08-28 09:44
I'm going to close this but feel free to continue commenting on it if you want to talk about the above more! 👍

**Closed as completed by olivierwilkinson** 2023-08-28 09:44 UTC
